from django.urls import path
from care.views import (
index,services,gallery,about,contact,jobs,NusrsingServices,
rehabilitationservicesinclude,nursinghomecriticalcarespecified,homeoncallhealthaides24hrs,homediagnosticlabandbloodtransfusionservices,homemedicalequipment,basicattendantnursingcare,assistantnursingcare,qualifiedregisterednursingcare,
specializednursingcare,postsurgicalnursingcare,poststrokenursingcare,maternitynursingcare,neonatalnursingcare,geriatricnursingcare,medicaloncologynursingcare,diabeticfootnursingcare,Childdaycarenursingcare,physicaltherapy,speechtherapy,psyhotherapy,respiratorytherapy,occupationaltherapy,cuppingtherapy_hijama,ECMtherapy,massagetherapy,diabeticfoottherapy,orthotics_prosthetics,diabeticcare,cardiaccare,maintainingintake,intravenoustherapy,untramuscularinjection,woundcareandprevention,bedsorescare,completetracheostomycare,COPDasthmaManagement,ora1medicationmanagement,onewgtubecare,PEGTubeCare,foleyscathetercare,ColostomyDrainageBagCare,nebulizerandsteamtherapy,pulseoximetry,diaperchanging,AssistwithBathing,perrectalevacuation,minorsurgicalprocedure,Homecollectionofbloodsamples,homeholtermonitor,ultrasoundathome,pelviscare,fetalcare,pregnancyusg,ECGathome,ECHOathome,vaccination,bloodtransfusion,BloodDonorsArrangement,OxygenatedAmbulanceServices,deliveryofreports,patientsbeds,cardiacmonitors,suctionmachines,BipapMachines,WheelChairs,Electricwheelchairs,Oxygencylinders,Glucometers,PulseOximeter,Spirometers,BloodPressureApparatus,Nebulizer,FirstAidBoxes,InfraredLights,BedsTables,onevStands,AirMattress,PatientsLifts,RollatorsWalkers,Crutches,AllSizesDiapers,AllSizesCatheters,CottonRolls,BedPansUrinals,DisposableGloves,SterilizedGauzes,oneVinfusions,)
urlpatterns = [
    path('', index, name="index"),
    path('services/', services, name="services"),
    path('gallery/', gallery, name="gallery"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
    path('jobs/', jobs, name="jobs"),
    path('NusrsingServices/', NusrsingServices, name="NursingServices"),
    path('rehabilitationservicesinclude/', rehabilitationservicesinclude, name="rehabilitationservicesinclude"),
    path('nursinghomecriticalcarespecified/', nursinghomecriticalcarespecified, name="nursinghomecriticalcarespecified"),
    path('homeoncallhealthaides24hrs/', homeoncallhealthaides24hrs, name="homeoncallhealthaides24hrs"),
    path('homediagnosticlabandbloodtransfusionservices/', homediagnosticlabandbloodtransfusionservices, name="homediagnosticlabandbloodtransfusionservices"),
    path('homemedicalequipment/', homemedicalequipment, name="homemedicalequipment"),
    path('basicattendantnursingcare/', basicattendantnursingcare, name="basicattendantnursingcare"),
    path('assistantnursingcare/', assistantnursingcare, name="assistantnursingcare"),
    path('qualifiedregisterednursingcare/', qualifiedregisterednursingcare, name="qualifiedregisterednursingcare"),
    path('specializednursingcare/', specializednursingcare, name="specializednursingcare"),
    path('postsurgicalnursingcare/', postsurgicalnursingcare, name="postsurgicalnursingcare"),
    # shuru
    path('poststrokenursingcare/', poststrokenursingcare, name="poststrokenursingcare"),
    path('maternitynursingcare/', maternitynursingcare, name="maternitynursingcare"),
    path('neonatalnursingcare/', neonatalnursingcare, name="neonatalnursingcare"),
    path('geriatricnursingcare/', geriatricnursingcare, name="geriatricnursingcare"),
    path('medicaloncologynursingcare/', medicaloncologynursingcare, name="medicaloncologynursingcare"),
    path('diabeticfootnursingcare/', diabeticfootnursingcare, name="diabeticfootnursingcare"),
    path('Childdaycarenursingcare/', Childdaycarenursingcare, name="Childdaycarenursingcare"),
    path('physicaltherapy/', physicaltherapy, name="physicaltherapy"),
    path('speechtherapy/', speechtherapy, name="speechtherapy"),
    path('psyhotherapy/', psyhotherapy, name="psyhotherapy"),
    path('respiratorytherapy/', respiratorytherapy, name="respiratorytherapy"),
    path('occupationaltherapy/', occupationaltherapy, name="occupationaltherapy"),
    path('cuppingtherapy_hijama/', cuppingtherapy_hijama, name="cuppingtherapy_hijama"),
    path('ECMtherapy/', ECMtherapy, name="ECMtherapy"),
    path('massagetherapy/', massagetherapy, name="massagetherapy"),
    path('diabeticfoottherapy/', diabeticfoottherapy, name="diabeticfoottherapy"),
    path('orthotics_prosthetics/', orthotics_prosthetics, name="orthotics_prosthetics"),
    path('diabeticcare/', diabeticcare, name="diabeticcare"),
    path('cardiaccare/', cardiaccare, name="cardiaccare"),
    path('maintainingintake/', maintainingintake, name="maintainingintake"),
    path('intravenoustherapy/', intravenoustherapy, name="intravenoustherapy"),
    path('untramuscularinjection/', untramuscularinjection, name="untramuscularinjection"),
    path('woundcareandprevention/', woundcareandprevention, name="woundcareandprevention"),
    path('bedsorescare/', bedsorescare, name="bedsorescare"),
    path('completetracheostomycare/', completetracheostomycare, name="completetracheostomycare"),
    path('COPDasthmaManagement/', COPDasthmaManagement, name="COPDasthmaManagement"),
    path('ora1medicationmanagement/', ora1medicationmanagement, name="ora1medicationmanagement"),
    path('onewgtubecare/', onewgtubecare, name="onewgtubecare"),
    path('PEGTubeCare/', PEGTubeCare, name="PEGTubeCare"),
    path('foleyscathetercare/', foleyscathetercare, name="foleyscathetercare"),
    path('ColostomyDrainageBagCare/', ColostomyDrainageBagCare, name="ColostomyDrainageBagCare"),
    path('nebulizerandsteamtherapy/', nebulizerandsteamtherapy, name="nebulizerandsteamtherapy"),
    path('pulseoximetry/', pulseoximetry, name="pulseoximetry"),
    path('diaperchanging/', diaperchanging, name="diaperchanging"),
    path('AssistwithBathing/', AssistwithBathing, name="AssistwithBathing"),
    path('perrectalevacuation/', perrectalevacuation, name="perrectalevacuation"),
    path('minorsurgicalprocedure/', minorsurgicalprocedure, name="minorsurgicalprocedure"),
    path('Homecollectionofbloodsamples/', Homecollectionofbloodsamples, name="Homecollectionofbloodsamples"),
    path('homeholtermonitor/', homeholtermonitor, name="homeholtermonitor"),
    path('ultrasoundathome/', ultrasoundathome, name="ultrasoundathome"),
    path('pelviscare/', pelviscare, name="pelviscare"),
    path('fetalcare/', fetalcare, name="fetalcare"),
    path('pregnancyusg/', pregnancyusg, name="pregnancyusg"),
    path('ECGathome/', ECGathome, name="ECGathome"),
    path('ECHOathome/', ECHOathome, name="ECHOathome"),
    path('vaccination/', vaccination, name="vaccination"),
    path('bloodtransfusion/', bloodtransfusion, name="bloodtransfusion"),
    path('BloodDonorsArrangement/', BloodDonorsArrangement, name="BloodDonorsArrangement"),
    path('OxygenatedAmbulanceServices/', OxygenatedAmbulanceServices, name="OxygenatedAmbulanceServices"),
    path('deliveryofreports/', deliveryofreports, name="deliveryofreports"),
    path('patientsbeds/', patientsbeds, name="patientsbeds"),
    path('cardiacmonitors/', cardiacmonitors, name="cardiacmonitors"),   
    path('suctionmachines/', suctionmachines, name="suctionmachines"), 
    path('BipapMachines/', BipapMachines, name="BipapMachines"),
    path('WheelChairs/', WheelChairs, name="WheelChairs"),
    path('Electricwheelchairs/', Electricwheelchairs, name="Electricwheelchairs"),
    path('Oxygencylinders/', Oxygencylinders, name="Oxygencylinders"),
    path('Glucometers/', Glucometers, name="Glucometers"),
    path('PulseOximeter/', PulseOximeter, name="PulseOximeter"),
    path('Spirometers/', Spirometers, name="Spirometers"),
    path('BloodPressureApparatus/', BloodPressureApparatus, name="BloodPressureApparatus"),
    path('Nebulizer/', Nebulizer, name="Nebulizer"),
    path('FirstAidBoxes/', FirstAidBoxes, name="FirstAidBoxes"),
    path('InfraredLights/', InfraredLights, name="InfraredLights"),
    path('BedsTables/', BedsTables, name="BedsTables"),
    path('onevStands/', onevStands, name="onevStands"),
    path('AirMattress/', AirMattress, name="AirMattress"),
    path('PatientsLifts/', PatientsLifts, name="PatientsLifts"),
    path('RollatorsWalkers/', RollatorsWalkers, name="RollatorsWalkers"),
    path('Crutches/', Crutches, name="Crutches"),
    path('AllSizesDiapers/', AllSizesDiapers, name="AllSizesDiapers"),
    path('AllSizesCatheters/', AllSizesCatheters, name="AllSizesCatheters"),
    path('CottonRolls/', CottonRolls, name="CottonRolls"),
    path('BedPansUrinals/', BedPansUrinals, name="BedPansUrinals"),
    path('DisposableGloves/', DisposableGloves, name="DisposableGloves"),
    path('SterilizedGauzes/', SterilizedGauzes, name="SterilizedGauzes"),
    path('oneVinfusions/', oneVinfusions, name="oneVinfusions"),







]